feat(ui): PrimaryButton
cs-zeus/superposition pull request #6
Opened 2021-10-15 11:45 UTC by zielu92

2021-10-15 11:58 UTC, Pittawat2542 requested changes
Please
1. Rebase from `main`
```
git pull --rebase origin main 
```
2. Ignore Jetbrain's IDE Setting files
3. Add screenshot
Thanks!

2021-10-16 08:39 UTC, Pittawat2542 requested changes
Please fix the following problems:
1. `.idea/` folder still showing up. :(
2. Be sure to rebase and force push
```
git pull --rebase origin main 
```
and then
```
git push -f origin PrimaryButton
```

2021-10-16 09:13 UTC, Pittawat2542 commented
> Thanks I fixed it already

Next time, don't forget to force push after rebase
```
git push -f origin PrimaryButton
```

2021-10-16 09:14 UTC, Pittawat2542 requested changes
I still seeing conflicts on `Index.tsx` and `package-lock.json` and `.idea/` folder still showing up. Please resolve these issues.

2021-10-16 09:58 UTC, Pittawat2542 requested changes
`.idea/` folder still show up.

try add [this](https://www.toptal.com/developers/gitignore/api/webstorm) to `.gitignore`

<img width="489" alt="image" src="https://user-images.githubusercontent.com/11158905/137583168-f9d97029-161a-476a-b345-66bd2d2ee1c4.png">

2021-10-16 09:58 UTC, Pittawat2542 commented on components/ui/PrimaryButton.tsx
> +  font-size: 1em;
This does not need

2021-10-16 09:58 UTC, Pittawat2542 commented on components/ui/PrimaryButton.tsx
> +  margin: 1em;
Don't use `em` with margin. Use `px` instead.

2021-10-16 09:58 UTC, Pittawat2542 commented on components/ui/PrimaryButton.tsx
> +  padding: 0.4em 2em;
Don't use `em` with margin. Use `px` instead.

2021-10-16 10:19 UTC, zielu92 commented
fixed styles

2021-10-16 10:33 UTC, merged